In [13]:
import numpy as np

flower_list = ['Dog', 'Cat', 'Rabbit']
print(flower_list)

values = []
for x in range(len(flower_list)):
    values.append(x)
print(values)

values_len = len(values)
print(values_len)

encoding = np.eye(values_len)[values]
print(encoding)

['Dog', 'Cat', 'Rabbit']
[0, 1, 2]
3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


NameError: name 'Okt' is not defined